# Generated by Django 2.2.7 on 2020-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200109_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
