# Generated by Django 2.2.7 on 2020-01-10 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_savedrecipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedrecipe',
            unique_together={('recipe', 'user')},
        ),
    ]
