# Generated by Django 2.2.7 on 2020-01-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20200110_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecipe',
            name='is_saved',
        ),
    ]
