# Generated by Django 2.2.7 on 2019-11-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('country', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('get_newsletter', models.BooleanField(default=False)),
            ],
        ),
    ]
